// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:sidequests/src/domain/entities/app_user.dart';
import 'package:sidequests/src/domain/entities/participant.dart';
import 'package:sidequests/src/domain/entities/side_quest.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(ParticipantAdapter());
    registerAdapter(SideQuestAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(ParticipantAdapter());
    registerAdapter(SideQuestAdapter());
  }
}
